### ISSUE TITLE
Settings not retained on Joplin restart

### ISSUE THREAD

**Issue by jahoyne** [personalizedrefrigerator/joplin-plugin-codemirror-6-snippets#2] opened 2024-04-27 16:30 UTC
Everything works as expected, put the Custom Snippets Note ID is not retained in the Settings following  a restart of Joplin.

Once the ID is re-entered in Settings the plug-in works again. 

<details>
<summary><b>Joplin Version and Plugins in use</b></summary>

Joplin 3.0.6 (prod, linux)

Client ID: 615c7880d02145c5a89371d6264bdcb9
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: 18b9f5c

Admonition markdown extension: 1.1.0
Backup: 1.4.1
CodeMirror 6 settings: 1.0.0
CodeMirror 6 snippets: 0.0.5
Conflict Resolution: 1.2.3
Copy Code Blocks: 1.1.0
Copy Universal Web Link: 0.1.0
Create and go to #tags and @notebooks: 1.3.7
Draw.io: 2.2.0
Embed Search: 2.0.0
Enhancement: 1.2.1
History Panel: 1.0.2
Home Note: 2.0.0
Hotfolder: 1.1.1
Inline tags: 1.3.0
Insert Date: 1.0.1
joplin-note-email: 1.0.5
joplin-plugin-TimelineRender: 1.0.2
Kminder Mindmap Joplin Plugin: 0.8.6
Markdown Prettier: 0.1.0
Markdown Table: Colorize: 1.2.0
Markdown Table: Sortable: 1.2.2
Markmap: 1.6.0
Menu items, Shortcuts, Toolbar icons: 1.1.0
Note Statistics: 1.0.4
Note Tabs: 1.4.0
Outline: 1.5.13
Paste Special: 1.1.2
Persistent Editor Layout: 2.2.0
PlantUML2: 1.11.0
Quick Links: 1.3.2
Quick Move: 1.1.0
Rich Markdown: 0.15.0
Spoilers: 1.0.6
Tagging: 1.0.3
Templates: 2.4.0
turnToChart: 1.9.3
VS-Code Style Note Search: 0.0.1
</details>

**Comment by personalizedrefrigerator** [comment] 2024-04-27 18:48
I'm linking to https://github.com/personalizedrefrigerator/joplin-plugin-extra-editor-settings/issues/1, which may be caused by the same upstream issue.

**Comment by personalizedrefrigerator** [comment] 2024-05-22 19:31
Upstream pull request: https://github.com/laurent22/joplin/pull/10458

**Comment by personalizedrefrigerator** [comment] 2024-06-12 20:03
The fix should be included in [Joplin 3.0.9](https://github.com/laurent22/joplin/releases/tag/v3.0.9). I plan to leave this open until v3.0.9 becomes stable.

Thank you for reporting this!

**Comment by personalizedrefrigerator** [comment] 2024-07-06 02:50
Joplin 3.0.x is now stable! I'm closing this as resolved.

**Closed as completed by personalizedrefrigerator** 2024-07-06 02:50 UTC
Labels: bug, upstream, upstream-fixed
